### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/forum_access#1]
As I started this, I did not fully think through the issue of dependancies. This module is dependent upon two other modules:

- [ACL](https://backdropcms.org/project/acl) - Available for Backdrop CMS
- [Chain Menu Access API](https://www.drupal.org/project/chain_menu_access) - NOT YET available for Backdrop CMS

For this module to be useful, someone will need to port Chain Menu Access API.

**Comment by herbdool** [comment]
Done. Though no official release since someone else can test.
