### ISSUE TITLE
Create an initial release

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/forum_access#12]
Testing now to see if this is ready for a release.

**Comment by stpaultim** [comment]
@VasasA - After initial testing, it seems to work for me. 

NOTE: I spend most of my testing time providing feedback on forum module. I tested this against the 1.x-1.x version of forum module, which has a few minor issues. I found there is a 1.x-2.x branch that is not yet stable, but something we should keep an eye on.

**Comment by VasasA** [comment]
Thank you, release is created.
