### ISSUE TITLE
Error when enabling Forum Access module

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/forum_access#16]
Error:
Argument 4 passed to chain_menu_access_chain() must be of the type array, bool given, called in /dev/server/myweb/backdrop/modules/forum_access/forum_access.module on line 60.

This happens immediately after enabling the Forum Access module, then the only way to get the site working again is to disable the module in the database and run update.php

My configuration:

Debian 10.1
Apache 2.4.38-3
MariaDB 10.3.18-0
PHP 7.3.11-1
Backdrop 1.14.1
Forum 1.x-1.0.2
ACL 1.x-1.0.0
Chain Menu Access API 1.x-2.1.0
Forum Access 1.x-1.4.0

**Comment by VasasA** [comment]
@and-e-h Thank you for the issue. I fixed it, and created a new release of Forum Access (1.x-1.4.1):
https://backdropcms.org/project/forum_access

**Comment by and-e-h** [comment]
@VasasA That looks like it did the trick! :) Many thanks for the swift response and fix.
