### ISSUE TITLE
Error on creation of a new forum

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/forum_access#8]
When I try to create a new forum, I get this error:

PDOException: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'anonymous' for column 'rid' at row 1: INSERT INTO {forum_access} (tid, rid, grant_view, grant_update, grant_delete, grant_create, priority) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6), (:db_insert_placeholder_7, :db_insert_placeholder_8, :db_insert_placeholder_9, :db_insert_placeholder_10, :db_insert_placeholder_11, :db_insert_placeholder_12, :db_insert_placeholder_13), (:db_insert_placeholder_14, :db_insert_placeholder_15, :db_insert_placeholder_16, :db_insert_placeholder_17, :db_insert_placeholder_18, :db_insert_placeholder_19, :db_insert_placeholder_20); Array ( [:db_insert_placeholder_0] => 3 [:db_insert_placeholder_1] => anonymous [:db_insert_placeholder_2] => 0 [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => 0 [:db_insert_placeholder_6] => 0 [:db_insert_placeholder_7] => 3 [:db_insert_placeholder_8] => authenticated [:db_insert_placeholder_9] => 0 [:db_insert_placeholder_10] => 0 [:db_insert_placeholder_11] => 0 [:db_insert_placeholder_12] => 0 [:db_insert_placeholder_13] => 0 [:db_insert_placeholder_14] => 3 [:db_insert_placeholder_15] => administrator [:db_insert_placeholder_16] => 0 [:db_insert_placeholder_17] => 0 [:db_insert_placeholder_18] => 0 [:db_insert_placeholder_19] => 0 [:db_insert_placeholder_20] => 0 ) in _forum_access_form_submit() (line 648 of /app/modules/forum_access/forum_access.admin.inc).

**Comment by herbdool** [comment]
Looks like might need to change rid to role and chance the column type to text instead of int. Then also need to help upgrade the old table to this new format: convert old rid to role. I'm not sure if that's easy. I think the old rid sticks around except for the anon and auth roles.

**Comment by stpaultim** [comment]
This seems to be resolved by work by @VasasA
