### ISSUE TITLE
Error every time I enable a new module

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/forum_access#9]
`Fatal error: Cannot redeclare forum_access_update_last_removed() (previously declared in /app/modules/forum_access/forum_access.install:183) in /app/modules/forum_access/forum_access.install on line 200`

**Comment by herbdool** [comment]
That's because there are two instances of the function. Remove the one for 6.

Also don't need any old update hooks.

**Comment by stpaultim** [comment]
This seems to be resolved by work by @VasasA
